# Keymap Autogenerated by Pog do not edit
from kmk.keys import KC
from kmk.modules.macros import Macros, Press, Release, Tap, Delay
from kmk.modules.combos import Chord, Sequence

import pog
import customkeys

keymap = [
    [
        KC.ESC,  KC.N1, KC.N2,  KC.N3,  KC.N4,   KC.N5,                                         KC.N6,  KC.N7,   KC.N8,   KC.N9,  KC.N0,   KC.QUOT,
        KC.TAB,  KC.Q,  KC.W,   KC.E,   KC.R,    KC.T,                                          KC.Y,   KC.U,    KC.I,    KC.O,   KC.P,    KC.MINS,
        KC.LGUI, KC.A,  KC.S,   KC.D,   KC.F,    KC.G,                                          KC.H,   KC.J,    KC.K,    KC.L,   KC.SCLN, KC.EQL,
        KC.LCTL, KC.Z,  KC.X,   KC.C,   KC.V,    KC.B,   KC.HOME,KC.END,    KC.PSCREEN, KC.CAPS,KC.N,    KC.M,    KC.COMM,KC.DOT,  KC.SLSH, KC.RSHIFT,
                 KC.GRV,KC.BSLS,KC.LEFT,KC.RIGHT,KC.SPC, KC.ENT, KC.PGUP,   KC.TAB,     KC.SPC, KC.BSPC, KC.DOWN, KC.UP,  KC.LBRC, KC.RBRC,
                                                                 KC.PGDOWN, KC.LALT
    ]
]

encoderKeymap = []
for l, layer in enumerate(pog.config['encoderKeymap']):
    layerEncoders = []
    for e, encoder in enumerate(layer):
        layerEncoders.append(tuple(map(eval, encoder)))
    encoderKeymap.append(tuple(layerEncoders))
